version: 2
jobs:
  build:
    docker:
      - image: 132265928525.dkr.ecr.ap-south-1.amazonaws.com/test:latest
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY_ID
    steps:
      - run:
          name: test
          command: |
           apt-get update
           
      
